/**
 * FULL Profile — PUBLIC 360 + PRIVATE Sections (Confidential)
 * Target: direction + équipe data/media (accès confidentiel).
 * Pages: 50-80.
 * PUBLIC sections + PRIVATE sections.
 * Visual separation: blue border for PUBLIC, red border for PRIVATE.
 * PRIVATE sections: GA4 detailed, conversions, Search Console, Ads, coherence.
 * "En clair" summaries on all major findings.
 * Confidential badges on private sections.
 */
export const FULL = {
  id: "full",
  name: "FULL — PUBLIC 360 + Données Privées",
  target: "Direction + équipe data/media (accès confidentiel)",
  tone: "business",
  lang: "fr",
  maxPages: 80,
  confidential: true,
  requiresPrivate: true,
  allowPrivateSections: true,
  sections: [
    // --- PUBLIC sections (blue border) ---
    "executive-summary",
    "scorecards",
    "performance",
    "seo-basics",
    "tracking-lite",
    "security-headers",
    "dns-infra",
    "robots-sitemap",
    "schema",
    "techstack",
    "crawler",
    "consent",
    "quick-wins",
    "risks",
    "backlog",
    "impact-effort-matrix",
    "compliance-checklist",
    "roadmap",
    // --- PRIVATE sections (red border) ---
    "ga4-detailed",
    "acquisition-channels",
    "landing-pages",
    "conversion-paths",
    "gsc-queries",
    "gsc-pages",
    "opportunities",
    "global-summary",
    "stratads-recommendation",
  ],
  privateSections: [
    "ga4-detailed",
    "acquisition-channels",
    "landing-pages",
    "conversion-paths",
    "gsc-queries",
    "gsc-pages",
    "opportunities",
  ],
  depth: "deep",
  tableTypes: [
    "quick-wins",
    "risk-register",
    "roadmap",
    "backlog",
    "impact-effort-matrix",
    "compliance-checklist",
    "page-comparison",
    "error-top",
    "top-queries",
    "top-pages",
    "anomalies",
    "underperforming-pages",
    "page-intent-mapping",
  ],
  chartTypes: [
    "score-donut",
    "pillar-bars",
    "cwv-bars",
    "cwv-distribution",
    "crawl-errors-bar",
    "tech-histogram",
    "channel-bars",
    "session-trend",
    "ctr-position-scatter",
  ],
  stratadsOffer: "full",
  annexes: true,
  humanSummaries: true,
  pptxSlides: [
    "cover",
    "executive-summary",
    "scorecards",
    "performance",
    "seo",
    "tracking",
    "security",
    "ga4",
    "gsc",
    "opportunities",
    "backlog",
    "roadmap",
    "stratads",
  ],
};
